### PR TITLE
Add gstreamer broadcaster

### PR DESCRIPTION
**Pull request by maruware**
Add a broadcaster script using gstreamer.

### CODE REVIEW

**Comment by ibc** [comment]
Interesting. May I get some help? Trying to run it in OSX with `gstreamer` installed via `Homebrew`. I've installed:

* `gstreamer` 1.16.2
* `gst-plugins-base`
* `gst-plugins-good`

When I run the script (which clearly uses VP8 to encode video) I get this fatal error:

```
Missing element: H.264 (Constrained Baseline Profile) decoder
ERROR: from element /GstPipeline:pipeline0/GstDecodeBin:decodebin0: Your GStreamer installation is missing a plug-in.
Additional debug info:
gstdecodebin2.c(4679): gboolean gst_decode_bin_expose(GstDecodeBin *) (): /GstPipeline:pipeline0/GstDecodeBin:decodebin0:
no suitable plugins found:
Missing decoder: H.264 (Constrained Baseline Profile) (video/x-h264, stream-format=(string)avc, alignment=(string)au, level=(string)3, profile=(string)constrained-baseline, codec_data=(buffer)0142c01effe1001a6742c01eda0280bfe5c05a808080a000007d20001d4c01e2c5d401000468ce3c80, width=(int)640, height=(int)360, framerate=(fraction)30000/1001, pixel-aspect-ratio=(fraction)1/1)
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...
```

Why should it need H264 decoder at all?

Then I've also installed `gst-plugins-bad`. Running the script now fails with:

```
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Redistribute latency...
ERROR: from element /GstPipeline:pipeline0/GstQTDemux:demux: Internal data stream error.
Additional debug info:
qtdemux.c(6605): gst_qtdemux_loop (): /GstPipeline:pipeline0/GstQTDemux:demux:
streaming stopped, reason not-negotiated (-4)
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...
```

**Comment by ibc** [comment]
In addition:

* I don't see any usage of `rtpbin` (or whatever, I do not know gstreamer) to enable RTCP-mux (so RTP and RTCP are sent with same source port), neither you are creating the plain transport with `rtcpMux: false`.

**Comment by maruware** [comment]
>Why should it need H264 decoder at all?

Because MEDIA_FILE is supposed mp4 and it is separated into video and audio,  each src is decoded, and is transported.

https://gstreamer.freedesktop.org/documentation/isomp4/qtdemux.html?gi-language=c

I installed gstreamer on OSX with

`brew install gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly`

The script worked and a video is displayed in Room at least.

**Comment by maruware** [comment]
>I don't see any usage of rtpbin (or whatever, I do not know gstreamer) to enable RTCP-mux (so RTP and RTCP are sent with same source port), neither you are creating the plain transport with rtcpMux: false.

I'll check it out.

**Comment by maruware** [comment]
I installed gstreamer on OSX with

`brew install gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly`

The script worked and a video is displayed in Room at least.

**Comment by ibc** [comment]
I've installed all those  `gst-xxx` packages via Homebrew and still get the same error:

```
ibc at ibc-macbook-pro in ~/src/v3-mediasoup-demo/broadcasters

$ SERVER_URL=https://MY-LOCAL-DOMAIN.org:4443 ROOM_ID=test MEDIA_FILE=../server/public/resources/videos/video-audio-stereo.mp4 ./gstreamer.sh

>>> verifying that room 'test' exists...
>>> creating Broadcaster...
>>> creating mediasoup PlainTransport for producing audio...
>>> creating mediasoup PlainTransport for producing video...
>>> creating mediasoup audio Producer...
>>> creating mediasoup video Producer...
>>> running GStreamer...
Warning: Failed to set locale category LC_NUMERIC to en_ES.
Warning: Failed to set locale category LC_TIME to en_ES.
Warning: Failed to set locale category LC_COLLATE to en_ES.
Warning: Failed to set locale category LC_MONETARY to en_ES.
Warning: Failed to set locale category LC_MESSAGES to en_ES.
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Redistribute latency...
ERROR: from element /GstPipeline:pipeline0/GstQTDemux:demux: Internal data stream error.
Additional debug info:
qtdemux.c(6605): gst_qtdemux_loop (): /GstPipeline:pipeline0/GstQTDemux:demux:
streaming stopped, reason not-negotiated (-4)
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...
>>> script exited with status code 1
```

Which media file are you testing with? Does it work for you using `server/public/resources/videos/video-audio-stereo.mp4`?

> The script worked and a video is displayed in Room at least.

What happens if a peer connects once gstreamer was **already** streaming? Does the new peer also see the video?

Since you are not setting `comedia` mode in the plain transports and do not specify RTCP settings in gstreamer, I bet gstreamer is NOT receiving any RTCP from mediasoup, meaning that NACKs and PLIs won't work.

**Comment by maruware** [comment]
It do not work also for me using `server/public/resources/videos/video-audio-stereo.mp4`.
I'll check it out.

I tested with a video downloaded from https://www.sample-videos.com/.

**Comment by maruware** [comment]
I'm sorry, I don't understand RTCP and mediasoup properly, but does the following look right?
(both succeeded to display video)

#### rtcpMux = undefined (true)

```sh
gst-launch-1.0 \
	rtpbin name=rtpbin \
	filesrc location=${MEDIA_FILE} \
	! qtdemux name=demux \
	demux.video_0 \
	! queue \
	! decodebin \
	! videoconvert \
	! vp8enc target-bitrate=1000000 deadline=1 cpu-used=4 \
	! rtpvp8pay pt=${VIDEO_PT} ssrc=${VIDEO_SSRC} picture-id-mode=2 \
	! rtpbin.send_rtp_sink_0 \
	rtpbin.send_rtp_src_0 ! udpsink host=${videoTransportIp} port=${videoTransportPort} \
	rtpbin.send_rtcp_src_0 ! udpsink host=${videoTransportIp} port=${videoTransportPort} sync=false async=false \
	demux.audio_0 \
	! queue \
	! decodebin \
	! audioconvert \
	! opusenc \
	! rtpopuspay pt=${AUDIO_PT} ssrc=${AUDIO_SSRC} \
	! rtpbin.send_rtp_sink_1 \
	rtpbin.send_rtp_src_1 ! udpsink host=${audioTransportIp} port=${audioTransportPort} \
    rtpbin.send_rtcp_src_1 ! udpsink host=${audioTransportIp} port=${videoTransportPort} sync=false async=false
```

#### rtcpMux = false

```sh

#...

res=$(${HTTPIE_COMMAND} \
	POST ${SERVER_URL}/rooms/${ROOM_ID}/broadcasters/${BROADCASTER_ID}/transports \
	type="plain" \
	comedia:=true \
	rtcpMux:=false \
	2> /dev/null)

#
# Parse JSON response into Shell variables and extract the PlainTransport id,
# IP and port.
#
eval "$(echo ${res} | jq -r '@sh "videoTransportId=\(.id) videoTransportIp=\(.ip) videoTransportPort=\(.port) videoRtcpPort=\(.rtcpPort)"')"

#...

gst-launch-1.0 \
	rtpbin name=rtpbin \
	filesrc location=${MEDIA_FILE} \
	! qtdemux name=demux \
	demux.video_0 \
	! queue \
	! decodebin \
	! videoconvert \
	! vp8enc target-bitrate=1000000 deadline=1 cpu-used=4 \
	! rtpvp8pay pt=${VIDEO_PT} ssrc=${VIDEO_SSRC} picture-id-mode=2 \
	! rtpbin.send_rtp_sink_0 \
	rtpbin.send_rtp_src_0 ! udpsink host=${videoTransportIp} port=${videoTransportPort} \
	rtpbin.send_rtcp_src_0 ! udpsink host=${videoTransportIp} port=${videoRtcpPort} sync=false async=false \
	demux.audio_0 \
	! queue \
	! decodebin \
	! audioconvert \
	! opusenc \
	! rtpopuspay pt=${AUDIO_PT} ssrc=${AUDIO_SSRC} \
	! rtpbin.send_rtp_sink_1 \
	rtpbin.send_rtp_src_1 ! udpsink host=${audioTransportIp} port=${audioTransportPort} \
    rtpbin.send_rtcp_src_1 ! udpsink host=${audioTransportIp} port=${audioRtcpPort} sync=false async=false
```

**Comment by maruware** [comment]
I've successfully broadcast using `server/public/resources/videos/video-audio-stereo.mp4` by adding `audioresample` plugin.

```sh
gst-launch-1.0 \
	rtpbin name=rtpbin \
	filesrc location=${MEDIA_FILE} \
	! qtdemux name=demux \
	demux.video_0 \
	! queue \
	! decodebin \
	! videoconvert \
	! vp8enc target-bitrate=1000000 deadline=1 cpu-used=4 \
	! rtpvp8pay pt=${VIDEO_PT} ssrc=${VIDEO_SSRC} picture-id-mode=2 \
	! rtpbin.send_rtp_sink_0 \
	rtpbin.send_rtp_src_0 ! udpsink host=${videoTransportIp} port=${videoTransportPort} \
	rtpbin.send_rtcp_src_0 ! udpsink host=${videoTransportIp} port=${videoTransportPort} sync=false async=false \
	demux.audio_0 \
	! queue \
	! decodebin \
	! audioresample \
	! audioconvert \
	! opusenc \
	! rtpopuspay pt=${AUDIO_PT} ssrc=${AUDIO_SSRC} \
	! rtpbin.send_rtp_sink_1 \
	rtpbin.send_rtp_src_1 ! udpsink host=${audioTransportIp} port=${audioTransportPort} \
    rtpbin.send_rtcp_src_1 ! udpsink host=${audioTransportIp} port=${videoTransportPort} sync=false async=false
```

**Comment by ibc** [comment]
Thanks. I've modified a bit the script (and also the previous `ffmpeg.sh`) to properly implement RTCP loca/dest ports:

https://github.com/versatica/mediasoup-demo/commit/56c369e43c92217aca082544c4c0603ac59d32d8

Merged and deployed in mediasoup-demo online app.

**Pull request closed without merging**
