### PR TITLE
Use Create React App

### PR DESCRIPTION
**Pull request by DylanVann**
- This could be broken into several PRs.
- This is missing a bit of functionality from `gulpfile.js`. I think mostly just missing opening windows with different query parameters, some scripts could be added to do that, or I could just put the gulpfile back, but only use it for those scripts, not for building the app.
- I think I could probably improve this so that HTTPS is easily handled across the app and server, right now it's not setup in an ideal way.
- I have tested this locally with the server, it appears to look and behave exactly the same.
  It would need to be tested more before merging though.

The developer experience of Create React App is very good IMO, as a more objective measure though I ran a Chrome performance audit on the production build before and after the switch to Create React App.

**Chrome performance audit before and after:**

image

### CODE REVIEW

**Comment by ibc** [comment]
I appreciate your work, however I'm afraid I don't wish to do apply so many changes to the demo. Adding all these changes would force me to learn all the new stuff you have introduced. This is just a demo application, not a product, and I'll need to maintain it and properly understand everything into it in the future. It will be more difficult if, in addition, I have to learn about `create-react-app` and all the other new stuff.

Again, I'm not against this, I strongly appreciate it and I may wish to merge this in the future once I'm more used to the new libs added by this PR. But not now (not yet). So, if you wish, I encourage you to finish working on this PR until it behaves, at least, as nicely as the original code (this includes replicating URL parameters, etc). Also, take into account that there is also an client application in the `aiortc/` folder. It looks like `app/` but without React stuff (it's a Node app). Obviously I don't want to maintain new code (`create-react-app`, etc( in `app/` and old code (`gulpfile`, `browserify`, etc) in `aiortc/`.

**Comment by DylanVann** [comment]
I understand it's a lot of changes. You might not need to learn as much as you think though. Create React App handles the `start` and `build` steps for you, instead of having to maintain things in Gulp. That's the majority of what it does. Other React frameworks work kind of the same, e.g. Next.js and Gatsby.

The thing about these frameworks is they usually don't support or encourage doing a lot of configuration, they support the happy path of React development. So for example CRA doesn't encourage the addition of extra Babel plugins like `babel-plugin-jsx-control-statements`, it supports SASS which is more widely used, but does not support Stylus. That's where most of the changes in this PR are coming from. If you want to move toward a more standard build system for the demo I could make these changes in separate PRs first so this one would seem more manageable.

I will look at trying to get those few scripts in the gulpfile working some other way and adding a better way to get HTTPS.

For the `aiortc` package there isn't the same amount of build setup as in `app`, right now there is no `gulpfile` or `browserify`. The way backend JS code is compiled/bundled is usually very different than how frontend JS code is compiled/bundled. Usually it's simpler, which is the case here. It uses `tsc` in watch mode and runs Node on the output, I would not change much about that.

**Comment by ibc** [comment]
Thanks for the explanation. However:

- I don't want to drop Stylus. I like Stylus more than SASS.
- I don't want to get rid of `gulp`. I use `gulp devel`, `gulp devel:tcp`, `gulp devel:vp9` many times a week to test mediasoup features. Those gulp tasks open two browser tabs with specific query params so a tab becomes producer and the other tab becomes consumer. I cannot get rid of this.

> CRA doesn't encourage the addition of extra Babel plugins like `babel-plugin-jsx-control-statements`

- So this means that I no longer can use `<If condition=xxx>` or `<Switch>`, which is super useful and friendly.

**Comment by DylanVann** [comment]
- Those scripts could be replicated, or even gulp could still be used to open up browser tabs.
- I guess if you definitely want to keep `<If>` and you definitely want to keep Stylus you could still use Create React App if you used `react-app-rewired`.
  - The docs for `babel-plugin-jsx-control-statements` do say now:
  > ☠️ Beware: This is a Babel plugin. It changes your code to other code - this means that some tooling that looks at your code (e.g. static analysis, typescript) is likely to not work. This plugin dates back to when JSX was daring and Javascript was more like playdough than meccano - if you want to stay on the well-trodden path stick with writing && and map.

I can take another look at this in a week or so, and maybe do it in a way that introduces less changes.

**Comment by DylanVann** [comment]
Possible PRs:

- Convert `babel-plugin-jsx-control-statements` to plain JavaScript.
  - The support for this syntax is not very good. I don't think it's worth the pain of setting it up in any other build system, especially if it's desired that it work with TypeScript.
  - I wrote [a codemod](https://github.com/DylanVann/dylans-codemods/blob/f275b58c1a2fcb7d1fd844f33cea51ed08b895d3/transforms/babel-plugin-jsx-control-statements-to-javascript.js#L42) to do this.
- There are a couple issues in the Stylus code that were revealed by setting it up in CRA. I could do a PR resolving these.
  - Syntax error in `Peer.styl`.
  - Warnings produced due to code in `nib`, this is only used for the reset, if we vendor the reset in and remove the dependency then we don't need to worry about them.

**Comment by ibc** [comment]
Hi, I'm very busy for some time. Will come back to this next week if possible. Thanks.

**Comment by namnm** [comment]
Hi, any news on this, do you guys need any help?
I would love to see create-react-app get merged too, but now its version is 4.x.
Look like this PR is a bit out of date.

**Comment by ibc** [comment]
I'm sorry. I appreciate the effort in this PR but I don't want to spend time learning new things just for the demo app that later will have to maintain. I don't have time, sorry.

**Comment by namnm** [comment]
Sorry to hear that, but I mean if you need help on maintaining this, we can help you on some aspects like this one for example.

**Comment by ibc** [comment]
I appreciate it, but honestly I don't have time to review so many changes and later maintain them in the future.

**Comment by poison** [comment]
Why not take this as another example app and include it in the examples section? https://mediasoup.org/documentation/examples/
I've been looking for these examples and they're hard to find, just my 2 cents!

**Comment by ibc** [comment]
> Why not take this as another example app and include it in the examples section? https://mediasoup.org/documentation/examples/

Who?

**Pull request closed without merging**
